基于vue框架的web前端报表查询功能制作
HIT-ReFreSH/WebLedger pull request #9
Opened 2024-11-03 14:52 UTC by Simon-like

Perform a certain level of decomposition and understanding of the business logic, and provide a basic web page based on Vue 3 + TypeScript + Pinia + Vue Router + Sass + Element Plus.

2024-11-03 14:53 UTC, Simon-like commented
![image](https://github.com/user-attachments/assets/279d47ac-942a-4b74-ada0-cfff5d6762f7)
![image](https://github.com/user-attachments/assets/9ccfc38f-0bf6-4ed6-83b2-231cab4babaf)
![image](https://github.com/user-attachments/assets/743efd35-927c-4955-9d3e-adcfa7323307)

2024-11-03 16:37 UTC, FerdinandSu requested changes
这些贡献几乎是完美的，只有一些小小的乌云（导致完全无法合并的一些啸问题），解决它们来成为这个仓库有史以来最有价值的PR吧。
1. 前端现在是整个放在了根目录下，导致代码的目录和后端重叠，这是不可接受的。请把他（以package.json所在的目录为根）放在仓库的client/或是frontend/这种地方。
2. 很多文件，如readme和gitignore有git合并标记，没有被去除，这也是不可接受的，引入它们会毁了整个仓库。

2024-11-03 16:37 UTC, FerdinandSu commented on .gitignore
git merge tokens should be removed

2024-11-03 16:37 UTC, FerdinandSu commented on README.md
git merge tokens should be removed

2024-11-03 16:37 UTC, FerdinandSu commented on README.md
just remove the vue‘s readme

2024-11-04 00:59 UTC, FerdinandSu requested changes
还是有一些致命问题：
1. Readme整个被删掉了
2. 前后端代码被重合得放置在了src/，实际上以package.json所在目录为根的前端要放在client（等单独的文件夹

2024-11-04 01:17 UTC, FerdinandSu approved these changes

2024-11-04 01:17 UTC, merged